@startuml
package SRP {
  class ClalucateSalary {
    - baseSalary: int
    - valueTime: int
    + ClalucateSalary(baseSalary: int, valueTime: int)
    + calculateSalary(): int
  }

  class Emploee {
    - name: String
    + Emploee(name: String)
    + toString(): String
  }

'  ClalucateSalary -- Emploee : employs
}
@enduml
